"""Sync schema check

Revision ID: 3be775e6c22c
Revises: 50c4eec7beb3
Create Date: 2026-07-22 20:51:18.774491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3be775e6c22c'
down_revision: Union[str, None] = '50c4eec7beb3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
