"""add email 2fa fields

Revision ID: 974a79ec9d92
Revises: add_trust_device
Create Date: 2026-08-15 20:41:12.264398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '974a79ec9d92'
down_revision: Union[str, None] = 'add_trust_device'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subscriptions')
    op.drop_index('ix_payments_tx_ref_status', table_name='payments')
    op.drop_index('ix_payments_user_status', table_name='payments')
    op.drop_table('payments')
    op.drop_table('pricing_plans')
    op.drop_index('ix_attempts_quiz_status', table_name='attempts')
    op.drop_index('ix_attempts_user_submitted', table_name='attempts')
    op.drop_index('ix_exam_questions_ai_generated', table_name='exam_questions')
    op.drop_index('ix_exam_questions_course_status', table_name='exam_questions')
    op.drop_index('ix_questions_course_type', table_name='questions')
    op.add_column('users', sa.Column('email_2fa_code', sa.String(length=10), nullable=True))
    op.add_column('users', sa.Column('email_2fa_expires', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'subscription_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment='When current premium subscription expires. NULL for lifetime.',
               existing_nullable=True)
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_index('ix_users_email_active', table_name='users')
    op.drop_index('ix_users_subscription', table_name='users')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_users_subscription', 'users', ['subscription_tier'], unique=False)
    op.create_index('ix_users_email_active', 'users', ['email', 'is_active'], unique=False)
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'subscription_expires_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               comment=None,
               existing_comment='When current premium subscription expires. NULL for lifetime.',
               existing_nullable=True)
    op.drop_column('users', 'email_2fa_expires')
    op.drop_column('users', 'email_2fa_code')
    op.create_index('ix_questions_course_type', 'questions', ['course_id', 'question_type'], unique=False)
    op.create_index('ix_exam_questions_course_status', 'exam_questions', ['course_id', 'review_status'], unique=False)
    op.create_index('ix_exam_questions_ai_generated', 'exam_questions', ['is_ai_generated'], unique=False)
    op.create_index('ix_attempts_user_submitted', 'attempts', ['student_id', 'submitted_at'], unique=False)
    op.create_index('ix_attempts_quiz_status', 'attempts', ['quiz_id', 'status'], unique=False)
    op.create_table('pricing_plans',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), server_default=sa.text("'Lifetime Premium'::character varying"), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('500.00'), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'ETB'::character varying"), autoincrement=False, nullable=False),
    sa.Column('duration_type', sa.VARCHAR(length=20), server_default=sa.text("'lifetime'::character varying"), autoincrement=False, nullable=False),
    sa.Column('duration_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_archived', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='pricing_plans_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('tx_ref', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('chapa_transaction_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'ETB'::character varying"), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'pending'::character varying"), autoincrement=False, nullable=False),
    sa.Column('checkout_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['pricing_plans.id'], name='payments_plan_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='payments_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='payments_pkey'),
    sa.UniqueConstraint('chapa_transaction_id', name='payments_chapa_transaction_id_key'),
    sa.UniqueConstraint('tx_ref', name='payments_tx_ref_key'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_payments_user_status', 'payments', ['user_id', 'status'], unique=False)
    op.create_index('ix_payments_tx_ref_status', 'payments', ['tx_ref', 'status'], unique=False)
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'active'::character varying"), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name='subscriptions_payment_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['pricing_plans.id'], name='subscriptions_plan_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='subscriptions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='subscriptions_pkey'),
    sa.UniqueConstraint('payment_id', name='subscriptions_payment_id_key')
    )
    # ### end Alembic commands ###
