"""add ai_usage_count to users table

Revision ID: 9bb891c0c6a8
Revises: 3be775e6c22c
Create Date: 2026-07-24 16:54:01.712435

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '9bb891c0c6a8'
down_revision: Union[str, None] = '3be775e6c22c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('ai_usage_count', sa.Integer(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'ai_usage_count')
    # ### end Alembic commands ###
