"""add missing user columns

Revision ID: ef21e39cd624
Revises: 2ae7e418c1a9
Create Date: 2026-08-13 00:57:51.691756

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'ef21e39cd624'
down_revision: Union[str, None] = '2ae7e418c1a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_progress')
    op.create_index(op.f('ix_ai_conversations_course_id'), 'ai_conversations', ['course_id'], unique=False)
    op.create_index(op.f('ix_ai_conversations_student_id'), 'ai_conversations', ['student_id'], unique=False)
    op.create_index('ix_ai_messages_conversation_created', 'ai_messages', ['conversation_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_ai_messages_conversation_id'), 'ai_messages', ['conversation_id'], unique=False)
    op.create_index(op.f('ix_ai_messages_flagged_topic'), 'ai_messages', ['flagged_topic'], unique=False)
    op.create_index(op.f('ix_announcements_is_pinned'), 'announcements', ['is_pinned'], unique=False)
    op.create_index('ix_announcements_pinned_created', 'announcements', ['is_pinned', 'created_at'], unique=False)
    op.create_index(op.f('ix_attempt_answers_attempt_id'), 'attempt_answers', ['attempt_id'], unique=False)
    op.create_index(op.f('ix_attempt_answers_question_id'), 'attempt_answers', ['question_id'], unique=False)
    op.create_index(op.f('ix_attempts_quiz_id'), 'attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_attempts_student_id'), 'attempts', ['student_id'], unique=False)
    op.create_index('ix_attempts_student_quiz', 'attempts', ['student_id', 'quiz_id'], unique=False)
    op.create_index(op.f('ix_course_materials_course_id'), 'course_materials', ['course_id'], unique=False)
    op.create_index(op.f('ix_courses_category'), 'courses', ['category'], unique=False)
    op.create_index(op.f('ix_courses_code'), 'courses', ['code'], unique=False)
    op.create_index(op.f('ix_courses_department_id'), 'courses', ['department_id'], unique=False)
    op.create_index('ix_courses_dept_order', 'courses', ['department_id', 'order_index'], unique=False)
    op.create_index(op.f('ix_departments_is_active'), 'departments', ['is_active'], unique=False)
    op.create_index(op.f('ix_departments_short_name'), 'departments', ['short_name'], unique=False)
    op.create_index(op.f('ix_drill_attempts_drill_id'), 'drill_attempts', ['drill_id'], unique=False)
    op.create_index(op.f('ix_exam_questions_course_id'), 'exam_questions', ['course_id'], unique=False)
    op.create_index(op.f('ix_exam_questions_created_by_id'), 'exam_questions', ['created_by_id'], unique=False)
    op.create_index(op.f('ix_exam_questions_is_ai_generated'), 'exam_questions', ['is_ai_generated'], unique=False)
    op.create_index(op.f('ix_exam_questions_review_status'), 'exam_questions', ['review_status'], unique=False)
    op.create_index(op.f('ix_exam_questions_reviewed_by_id'), 'exam_questions', ['reviewed_by_id'], unique=False)
    op.create_index('ix_exam_questions_status_course', 'exam_questions', ['review_status', 'course_id'], unique=False)
    op.create_index(op.f('ix_learning_materials_course_id'), 'learning_materials', ['course_id'], unique=False)
    op.create_index(op.f('ix_learning_materials_is_public'), 'learning_materials', ['is_public'], unique=False)
    op.create_index(op.f('ix_learning_materials_status'), 'learning_materials', ['status'], unique=False)
    op.create_index('ix_learning_materials_status_public', 'learning_materials', ['status', 'is_public'], unique=False)
    op.create_index(op.f('ix_learning_materials_topic_id'), 'learning_materials', ['topic_id'], unique=False)
    op.create_index(op.f('ix_learning_materials_uploaded_by_id'), 'learning_materials', ['uploaded_by_id'], unique=False)
    op.create_index(op.f('ix_password_reset_tokens_user_id'), 'password_reset_tokens', ['user_id'], unique=False)
    op.create_index('ix_questions_course_difficulty', 'questions', ['course_id', 'difficulty'], unique=False)
    op.create_index(op.f('ix_questions_course_id'), 'questions', ['course_id'], unique=False)
    op.create_index(op.f('ix_questions_topic_id'), 'questions', ['topic_id'], unique=False)
    op.create_index(op.f('ix_quiz_questions_question_id'), 'quiz_questions', ['question_id'], unique=False)
    op.create_index(op.f('ix_quiz_questions_quiz_id'), 'quiz_questions', ['quiz_id'], unique=False)
    op.create_index('ix_quiz_questions_quiz_order', 'quiz_questions', ['quiz_id', 'order_index'], unique=False)
    op.create_index(op.f('ix_quizzes_course_id'), 'quizzes', ['course_id'], unique=False)
    op.create_index(op.f('ix_quizzes_generated_for_user_id'), 'quizzes', ['generated_for_user_id'], unique=False)
    op.create_index(op.f('ix_topics_course_id'), 'topics', ['course_id'], unique=False)
    op.create_index('ix_topics_course_order', 'topics', ['course_id', 'order_index'], unique=False)
    op.alter_column('user_devices', 'last_active',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=False)
    op.drop_index('ix_user_devices_user_id', table_name='user_devices')
    op.drop_index('ix_user_devices_session_jti', table_name='user_devices')
    op.create_index(op.f('ix_user_devices_session_jti'), 'user_devices', ['session_jti'], unique=True)
    op.add_column('users', sa.Column('subscription_expires_at', sa.DateTime(timezone=True), nullable=True))
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.create_index(op.f('ix_users_is_active'), 'users', ['is_active'], unique=False)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_index(op.f('ix_users_subscription_tier'), 'users', ['subscription_tier'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_subscription_tier'), table_name='users')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_is_active'), table_name='users')
    op.alter_column('users', 'failed_login_attempts',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.drop_column('users', 'subscription_expires_at')
    op.drop_index(op.f('ix_user_devices_session_jti'), table_name='user_devices')
    op.create_index('ix_user_devices_session_jti', 'user_devices', ['session_jti'], unique=False)
    op.create_index('ix_user_devices_user_id', 'user_devices', ['user_id'], unique=False)
    op.alter_column('user_devices', 'last_active',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=False)
    op.drop_index('ix_topics_course_order', table_name='topics')
    op.drop_index(op.f('ix_topics_course_id'), table_name='topics')
    op.drop_index(op.f('ix_quizzes_generated_for_user_id'), table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_course_id'), table_name='quizzes')
    op.drop_index('ix_quiz_questions_quiz_order', table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_quiz_id'), table_name='quiz_questions')
    op.drop_index(op.f('ix_quiz_questions_question_id'), table_name='quiz_questions')
    op.drop_index(op.f('ix_questions_topic_id'), table_name='questions')
    op.drop_index(op.f('ix_questions_course_id'), table_name='questions')
    op.drop_index('ix_questions_course_difficulty', table_name='questions')
    op.drop_index(op.f('ix_password_reset_tokens_user_id'), table_name='password_reset_tokens')
    op.drop_index(op.f('ix_learning_materials_uploaded_by_id'), table_name='learning_materials')
    op.drop_index(op.f('ix_learning_materials_topic_id'), table_name='learning_materials')
    op.drop_index('ix_learning_materials_status_public', table_name='learning_materials')
    op.drop_index(op.f('ix_learning_materials_status'), table_name='learning_materials')
    op.drop_index(op.f('ix_learning_materials_is_public'), table_name='learning_materials')
    op.drop_index(op.f('ix_learning_materials_course_id'), table_name='learning_materials')
    op.drop_index('ix_exam_questions_status_course', table_name='exam_questions')
    op.drop_index(op.f('ix_exam_questions_reviewed_by_id'), table_name='exam_questions')
    op.drop_index(op.f('ix_exam_questions_review_status'), table_name='exam_questions')
    op.drop_index(op.f('ix_exam_questions_is_ai_generated'), table_name='exam_questions')
    op.drop_index(op.f('ix_exam_questions_created_by_id'), table_name='exam_questions')
    op.drop_index(op.f('ix_exam_questions_course_id'), table_name='exam_questions')
    op.drop_index(op.f('ix_drill_attempts_drill_id'), table_name='drill_attempts')
    op.drop_index(op.f('ix_departments_short_name'), table_name='departments')
    op.drop_index(op.f('ix_departments_is_active'), table_name='departments')
    op.drop_index('ix_courses_dept_order', table_name='courses')
    op.drop_index(op.f('ix_courses_department_id'), table_name='courses')
    op.drop_index(op.f('ix_courses_code'), table_name='courses')
    op.drop_index(op.f('ix_courses_category'), table_name='courses')
    op.drop_index(op.f('ix_course_materials_course_id'), table_name='course_materials')
    op.drop_index('ix_attempts_student_quiz', table_name='attempts')
    op.drop_index(op.f('ix_attempts_student_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempts_quiz_id'), table_name='attempts')
    op.drop_index(op.f('ix_attempt_answers_question_id'), table_name='attempt_answers')
    op.drop_index(op.f('ix_attempt_answers_attempt_id'), table_name='attempt_answers')
    op.drop_index('ix_announcements_pinned_created', table_name='announcements')
    op.drop_index(op.f('ix_announcements_is_pinned'), table_name='announcements')
    op.drop_index(op.f('ix_ai_messages_flagged_topic'), table_name='ai_messages')
    op.drop_index(op.f('ix_ai_messages_conversation_id'), table_name='ai_messages')
    op.drop_index('ix_ai_messages_conversation_created', table_name='ai_messages')
    op.drop_index(op.f('ix_ai_conversations_student_id'), table_name='ai_conversations')
    op.drop_index(op.f('ix_ai_conversations_course_id'), table_name='ai_conversations')
    op.create_table('student_progress',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('student_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('quizzes_taken', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('average_score_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('mastery_percent', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('last_activity_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='student_progress_course_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], name='student_progress_student_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='student_progress_pkey'),
    sa.UniqueConstraint('student_id', 'course_id', name='uq_student_course_progress')
    )
    # ### end Alembic commands ###
