"""Add last_ai_usage_date to users

Revision ID: fb8d25280727
Revises: add_note_review_workflow
Create Date: 2026-08-21 16:54:53.757868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'fb8d25280727'
down_revision: Union[str, None] = 'add_note_review_workflow'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_payments_plan_id', table_name='payments')
    op.drop_index('ix_payments_status', table_name='payments')
    op.drop_index('ix_payments_tx_ref', table_name='payments')
    op.drop_index('ix_payments_user_id', table_name='payments')
    op.drop_table('payments')
    op.drop_table('pricing_plans')
    op.drop_index('ix_subscriptions_status', table_name='subscriptions')
    op.drop_index('ix_subscriptions_user_id', table_name='subscriptions')
    op.drop_table('subscriptions')
    op.drop_table('code_trace_drills')
    op.drop_table('flashcards')
    op.create_foreign_key(None, 'course_notes', 'users', ['reviewed_by_id'], ['id'])
    op.add_column('users', sa.Column('last_ai_usage_date', sa.DateTime(), nullable=True))
    op.alter_column('users', 'last_active',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'last_active',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('users', 'last_ai_usage_date')
    op.drop_constraint(None, 'course_notes', type_='foreignkey')
    op.create_table('flashcards',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('course_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('note_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('front', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('back', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('exam_weight', sa.VARCHAR(length=10), server_default=sa.text("'MEDIUM'::character varying"), autoincrement=False, nullable=True),
    sa.Column('module_title', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'APPROVED'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], name='flashcards_course_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='flashcards_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['note_id'], ['course_notes.id'], name='flashcards_note_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='flashcards_pkey')
    )
    op.create_table('code_trace_drills',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('subject', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('topic', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('code_snippet', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('language', sa.VARCHAR(length=10), server_default=sa.text("'cpp'::character varying"), autoincrement=False, nullable=True),
    sa.Column('total_steps', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('trace_steps', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('exit_exam_question', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('correct_option_index', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('distractor_explanation', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('difficulty', sa.VARCHAR(length=10), server_default=sa.text("'medium'::character varying"), autoincrement=False, nullable=True),
    sa.Column('priority', sa.VARCHAR(length=10), server_default=sa.text("'HIGH'::character varying"), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), server_default=sa.text("'DRAFT'::character varying"), autoincrement=False, nullable=True),
    sa.Column('source_type', sa.VARCHAR(length=20), server_default=sa.text("'ai_generated'::character varying"), autoincrement=False, nullable=True),
    sa.Column('created_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reviewed_by_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], name='code_trace_drills_created_by_id_fkey'),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], name='code_trace_drills_reviewed_by_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='code_trace_drills_pkey')
    )
    op.create_table('subscriptions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payment_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('active', 'expired', 'cancelled', 'pending', name='subscription_status'), autoincrement=False, nullable=False),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('expires_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True, comment='NULL for lifetime subscriptions'),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name='subscriptions_payment_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['plan_id'], ['pricing_plans.id'], name='subscriptions_plan_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='subscriptions_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='subscriptions_pkey'),
    sa.UniqueConstraint('payment_id', name='subscriptions_payment_id_key')
    )
    op.create_index('ix_subscriptions_user_id', 'subscriptions', ['user_id'], unique=False)
    op.create_index('ix_subscriptions_status', 'subscriptions', ['status'], unique=False)
    op.create_table('pricing_plans',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), server_default=sa.text("'Premium Lifetime'::character varying"), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), server_default=sa.text('500.00'), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), server_default=sa.text("'ETB'::character varying"), autoincrement=False, nullable=False),
    sa.Column('duration_type', sa.VARCHAR(length=20), server_default=sa.text("'lifetime'::character varying"), autoincrement=False, nullable=False),
    sa.Column('duration_value', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('features', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=False),
    sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False),
    sa.Column('is_archived', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pricing_plans_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('plan_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('tx_ref', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('chapa_transaction_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('amount', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False),
    sa.Column('currency', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('status', postgresql.ENUM('pending', 'success', 'failed', 'cancelled', 'expired', name='payment_status'), autoincrement=False, nullable=False),
    sa.Column('checkout_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('payment_method', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('verified_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['plan_id'], ['pricing_plans.id'], name='payments_plan_id_fkey', ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='payments_user_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='payments_pkey'),
    sa.UniqueConstraint('chapa_transaction_id', name='payments_chapa_transaction_id_key')
    )
    op.create_index('ix_payments_user_id', 'payments', ['user_id'], unique=False)
    op.create_index('ix_payments_tx_ref', 'payments', ['tx_ref'], unique=True)
    op.create_index('ix_payments_status', 'payments', ['status'], unique=False)
    op.create_index('ix_payments_plan_id', 'payments', ['plan_id'], unique=False)
    # ### end Alembic commands ###
